kind: Service
apiVersion: v1
metadata:
  name: customerSvc-service
spec:
  type: NodePort
  selector:
    app: customerSvc
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customerSvc-deployment
  labels:
    app: customerSvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customerSvc
  template:
    metadata:
      labels:
        app: customerSvc
    spec:
      containers:
      - name: customerSvc
        image: $IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080